import { StyleSheet } from "react-native";
import { C } from "../view-plans.styles";

export default StyleSheet.create({
  safe: { flex: 1, justifyContent: "flex-end" },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.6)",
    zIndex: 40,
  },
  sheet: {
    zIndex: 50,
    backgroundColor: C.surfaceContainer || "#0e0e0e",
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    maxHeight: "92%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -12 },
    shadowOpacity: 0.6,
    elevation: 20,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
  },
  dragHandleContainer: {
    display: "flex",
    alignItems: "center",
    paddingTop: 16,
    paddingBottom: 4,
  },
  dragHandle: {
    width: 40,
    height: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
  },
  title: { fontSize: 24, fontWeight: "800", color: C.onSurface },
  closeBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: C.surfaceContainerHigh || "rgba(255,255,255,0.02)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  content: { paddingHorizontal: 20, paddingBottom: 160, paddingTop: 8 },
  obsidianCard: {
    backgroundColor: C.surfaceContainerLow || "#1c1b1b",
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    marginBottom: 24,
  },
  pricingHero: { display: "flex", gap: 24 },
  priceDisplay: { flexDirection: "row", alignItems: "baseline", gap: 6 },
  priceAmount: {
    fontSize: 48,
    fontWeight: "800",
    color: C.primary,
    lineHeight: 48,
  },
  pricePeriod: {
    fontSize: 14,
    fontWeight: "500",
    color: C.onSurfaceVariant,
    marginLeft: 6,
  },
  badgeActive: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(179,197,255,0.06)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    marginTop: 12,
    borderWidth: 1,
    borderColor: "rgba(179,197,255,0.2)",
  },
  badgeText: {
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
    color: "rgba(179,197,255,0.9)",
  },
  metricGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
  },
  vaultItem: {
    flex: 1,
    backgroundColor: C.surface || "#131313",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.04)",
    marginRight: 12,
  },
  metricLabel: {
    fontSize: 10,
    textTransform: "uppercase",
    fontWeight: "800",
    color: C.onSurfaceVariant,
  },
  metricValue: {
    fontSize: 18,
    fontWeight: "800",
    color: C.onSurface,
    marginTop: 6,
  },
  metricAccentBar: { height: 2, width: 32, marginTop: 8, borderRadius: 999 },
  bgPrimaryBar: { backgroundColor: "rgba(219,226,255,0.4)" },
  bgSecondaryBar: { backgroundColor: "rgba(78,222,163,0.4)" },
  sectionDividerArea: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  sectionDividerAreaSingle: { marginTop: 12, marginBottom: 12 },
  dividerLine: { flex: 1, height: 1, backgroundColor: "rgba(69,70,79,0.5)" },
  sectionLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: C.onSurfaceVariant,
    textTransform: "uppercase",
    letterSpacing: 2,
    textAlign: "center",
  },
  iconGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    marginBottom: 24,
  },
  iconUnit: { alignItems: "center" },
  iconContainer: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: C.surface || "#131313",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  iconText: {
    fontSize: 11,
    fontWeight: "700",
    marginTop: 8,
    color: C.onSurface,
  },
  benefitList: { marginTop: 8, marginBottom: 8 },
  benefitCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    backgroundColor: C.surfaceContainerLow || "#1c1b1b",
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    marginBottom: 12,
  },
  benefitIconBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: C.surfaceContainerHighest || "#353534",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  benefitContent: { flex: 1 },
  benefitTitle: { fontSize: 14, fontWeight: "700", color: C.onSurface },
  benefitSubtitle: { fontSize: 12, color: C.onSurfaceVariant, marginTop: 4 },
  finePrintCard: {
    flexDirection: "row",
    gap: 8,
    backgroundColor: C.surfaceContainerLow || "#1c1b1b",
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    marginTop: 16,
    marginBottom: 28,
  },
  finePrintTextWrap: { marginLeft: 6 },
  finePrintText: {
    color: C.onSurfaceVariant,
    fontSize: 11,
    lineHeight: 18,
    marginBottom: 6,
  },
  footerAction: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    padding: 20,
    backgroundColor: C.surfaceContainer || "#0e0e0e",
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
    zIndex: 60,
  },
  payButton: {
    width: "100%",
    height: 64,
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#0055d5",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    elevation: 8,
  },
  payButtonInner: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
  },
  payButtonLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "rgba(255,255,255,0.9)",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  payButtonValue: { fontSize: 20, fontWeight: "800", color: "white" },
  payButtonIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
});
