import { StyleSheet } from "react-native";
import { C, S } from "./(tabs)/index.styles";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: C.background },
  header: {
    width: "100%",
    zIndex: 50,
    backgroundColor: "rgba(19,19,19,0.8)",
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    paddingVertical: 12,
    paddingHorizontal: S.marginMobile,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerLeft: { flexDirection: "row", alignItems: "center", gap: S.md },
  headerTitle: { fontSize: 20, fontWeight: "700", color: C.onSurface },
  btnBack: {
    backgroundColor: "transparent",
    padding: 8,
    borderRadius: 999,
  },
  btnTextAction: { padding: 8 },
  btnTextActionText: { color: C.primary, fontSize: 14, fontWeight: "500" },
  main: {
    paddingTop: 80,
    paddingHorizontal: S.marginMobile,
    paddingBottom: 120,
    gap: 32,
    maxWidth: 600,
    alignSelf: "center",
  },
  section: { marginBottom: 32 },
  sectionTitle: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.1,
    color: C.onSurfaceVariant,
    marginBottom: 16,
    paddingLeft: 4,
  },
  notificationCard: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    padding: 16,
    marginBottom: 12,
    flexDirection: "row",
    gap: 16,
    position: "relative",
    overflow: "hidden",
  },
  unreadCard: {},
  unreadBar: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
    backgroundColor: C.secondary,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
  },
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: C.surfaceContainer,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  content: { flexGrow: 1 },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 4,
  },
  title: { fontSize: 16, fontWeight: "600", color: C.onSurface },
  time: { fontSize: 12, color: C.onSurfaceVariant },
  description: {
    fontSize: 14,
    color: C.onSurfaceVariant,
    marginBottom: 8,
    lineHeight: 20,
  },
  badgeRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: C.secondary,
  },
  statusText: { fontSize: 12, fontWeight: "600", color: C.secondary },
  statusSuccess: { color: C.secondary },
  statusPending: { color: "#ffb95f" },
  statusFailed: { color: C.error },
  btnPrimary: {
    backgroundColor: C.secondary,
    color: C.onPrimary,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginTop: 8,
    alignSelf: "flex-start",
  },
});
