export const labels = {
  title: "Plan Details",
  activeMembershipBadge: "Active Membership",
  duration: "Duration",
  dailyLimit: "Daily Limit",
  curatedSuites: "Curated Suites",
  infrastructureAccess: "Infrastructure Access",
  authorizeTransaction: "Authorize Transaction",
  payPrefix: "Pay",
  benefits: [
    {
      key: "unlimited-5g",
      short: "5G",
      title: "Unlimited True 5G",
      subtitle: "Premier low-latency bandwidth",
      priority: 1,
    },
    {
      key: "hd-voice",
      short: "HD",
      title: "HD Voice Calls",
      subtitle: "Unlimited nationwide crystal-clear calling",
      priority: 2,
    },
    {
      key: "sms-bundle",
      short: "MSG",
      title: "Digital Messaging",
      subtitle: "SMS bundle included per cycle",
      priority: 3,
    },
    {
      key: "extra-data",
      short: "DATA",
      title: "Extra Data",
      subtitle: "Additional data quota included",
      priority: 4,
    },
    {
      key: "verified-service",
      short: "OK",
      title: "Verified Service",
      subtitle: "Official certified benefits",
      priority: 5,
    },
    {
      key: "ott-access",
      short: "OTT",
      title: "OTT Access",
      subtitle: "Access to popular streaming services",
      priority: 6,
    },
    {
      key: "gaming",
      short: "GAME",
      title: "Gaming Perks",
      subtitle: "Low-latency gaming access",
      priority: 7,
    },
    {
      key: "roaming",
      short: "ROAM",
      title: "Roaming Packs",
      subtitle: "International roaming benefits",
      priority: 8,
    },
    {
      key: "cloud",
      short: "CLOUD",
      title: "Cloud Storage",
      subtitle: "Included cloud backup",
      priority: 9,
    },
    {
      key: "priority-support",
      short: "PRIO",
      title: "Priority Support",
      subtitle: "Premium customer support",
      priority: 10,
    },
    {
      key: "daily-cap",
      short: "CAP",
      title: "Daily Limit",
      subtitle: "Daily data limit applies",
      priority: 11,
    },
  ],
  finePrint: [
    "FUP applies: Data speed resets to 64 Kbps after daily quota.",
    "5G availability is subject to network coverage and compatible devices.",
    "All plans include regulatory taxes and standard service agreements.",
  ],
};

export default labels;
