import { StyleSheet } from "react-native";

export const C = {
  background: "#0A0A0A",
  surface: "#131313",
  surfaceContainer: "#201f1f",
  surfaceContainerHighest: "#353534",
  onSurface: "#e5e2e1",
  onSurfaceVariant: "#c2c6d8",
  primary: "#b3c5ff",
  primaryContainer: "#5e8bff",
  inversePrimary: "#0055d5",
  secondary: "#4edea3",
  tertiary: "#ffb95f",
  error: "#ffb4ab",
  outline: "#8c90a1",
  glass: "rgba(26, 26, 26, 0.7)" as const,
  border: "rgba(255, 255, 255, 0.08)" as const,
};

export const S = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  marginMobile: 20,
};

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#0A0A0A",
  },

  // ── Header ──────────────────────────────────────────────────────────────
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: S.marginMobile,
    paddingVertical: S.sm,
    backgroundColor: "rgba(13, 13, 13, 0.85)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  greeting: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    letterSpacing: 0.24,
    color: "#8c90a1",
  },
  userName: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
    letterSpacing: 0.14,
    color: "#e5e2e1",
  },
  notificationBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#201f1f",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  notificationBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#ffb4ab",
  },

  // ── ScrollView ──────────────────────────────────────────────────────────
  scroll: { flex: 1 },
  scrollContent: {
    paddingHorizontal: S.marginMobile,
    paddingTop: S.xl,
    paddingBottom: 140,
    gap: S.xl,
  },

  // ── Glass card base (used for quick-action buttons) ─────────────────────
  glassCard: {
    backgroundColor: "rgba(26, 26, 26, 0.7)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },

  // ── Smart Insight Banner ────────────────────────────────────────────────
  insightBanner: {
    borderRadius: 12,
    padding: S.md,
    flexDirection: "row",
    alignItems: "center",
    gap: S.md,
    backgroundColor: "rgba(26, 26, 26, 0.7)",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 2,
    borderTopColor: "rgba(255, 255, 255, 0.08)",
    borderRightColor: "rgba(255, 255, 255, 0.08)",
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
    borderLeftColor: "#b3c5ff",
    overflow: "hidden",
  },
  insightIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(94, 139, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  insightTitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
    color: "#b3c5ff",
  },
  insightBody: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    color: "#c2c6d8",
    marginTop: S.xs,
  },

  // ── Hero Card ───────────────────────────────────────────────────────────
  heroCard: {
    borderRadius: 16,
    padding: S.lg,
    backgroundColor: "rgba(26, 26, 26, 0.7)",
    borderTopWidth: 1,
    borderTopColor: "rgba(179, 197, 255, 0.3)",
    borderRightWidth: 1,
    borderRightColor: "rgba(255, 255, 255, 0.08)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
    borderLeftWidth: 1,
    borderLeftColor: "rgba(255, 255, 255, 0.08)",
    overflow: "hidden",
  },
  heroGlow: {
    position: "absolute",
    top: -96,
    right: -96,
    width: 256,
    height: 256,
    borderRadius: 128,
    backgroundColor: "rgba(179, 197, 255, 0.07)",
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: S.lg,
  },
  heroLeft: {
    flex: 1,
  },
  expiryBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    backgroundColor: "rgba(202, 129, 0, 0.2)",
    borderWidth: 1,
    borderColor: "rgba(255, 185, 95, 0.3)",
    alignSelf: "flex-start",
  },
  expiryDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#ffb95f",
  },
  expiryText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#ffb95f",
    letterSpacing: 0.1,
    textTransform: "uppercase",
  },
  phoneNumber: {
    fontSize: 24,
    lineHeight: 32,
    letterSpacing: -0.24,
    fontWeight: "600",
    color: "#e5e2e1",
    marginTop: S.sm,
  },
  planRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
  },
  planDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#b3c5ff",
  },
  planName: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    color: "#c2c6d8",
  },

  // ── Progress Ring ───────────────────────────────────────────────────────
  progressRingWrap: {
    width: 128,
    height: 128,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  progressCenter: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
  },
  progressPercent: {
    fontSize: 24,
    fontWeight: "700",
    lineHeight: 32,
    color: "#ffb95f",
  },
  progressLabel: {
    fontSize: 12,
    fontWeight: "500",
    color: "#c2c6d8",
    textTransform: "uppercase",
    letterSpacing: 1,
  },

  // ── Stats grid ──────────────────────────────────────────────────────────
  statsGrid: {
    flexDirection: "row",
    gap: S.md,
    marginBottom: S.lg,
  },
  statCard: {
    flex: 1,
    backgroundColor: "rgba(32, 31, 31, 0.5)",
    borderRadius: 8,
    padding: S.sm,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  statLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    color: "#8c90a1",
  },
  statValue: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
    color: "#e5e2e1",
    marginTop: 2,
  },

  // ── CTA Button ──────────────────────────────────────────────────────────
  ctaWrapper: {
    borderRadius: 8,
    overflow: "hidden",
    shadowColor: "#0055d5",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 10,
  },
  ctaButton: {
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  ctaButtonText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
    color: "white",
    letterSpacing: 0.14,
  },

  // ── Quick Actions ───────────────────────────────────────────────────────
  actionsGrid: {
    gap: S.md,
  },
  actionsRow: {
    flexDirection: "row",
    gap: S.md,
  },
  actionBtn: {
    flex: 1,
    borderRadius: 12,
    padding: S.md,
    alignItems: "center",
    justifyContent: "center",
    gap: S.sm,
    minHeight: 100,
  },
  actionIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  actionLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    color: "#e5e2e1",
    textAlign: "center",
  },

  // ── Upcoming Queue ──────────────────────────────────────────────────────
  queueHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: S.md,
  },
  queueTitle: {
    fontSize: 24,
    lineHeight: 32,
    letterSpacing: -0.24,
    fontWeight: "600",
    color: "#e5e2e1",
  },
  queueViewAll: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    color: "#b3c5ff",
  },
  queueItems: {
    gap: S.sm,
  },
  queueItem: {
    borderRadius: 8,
    padding: S.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(26, 26, 26, 0.7)",
  },
  queueItemPending: {
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 2,
    borderTopColor: "rgba(255, 255, 255, 0.08)",
    borderRightColor: "rgba(255, 255, 255, 0.08)",
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
    borderLeftColor: "#b3c5ff",
  },
  queueItemCompleted: {
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 2,
    borderTopColor: "rgba(255, 255, 255, 0.08)",
    borderRightColor: "rgba(255, 255, 255, 0.08)",
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
    borderLeftColor: "#4edea3",
    opacity: 0.75,
  },
  queueItemFailed: {
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 2,
    borderTopColor: "rgba(255, 255, 255, 0.08)",
    borderRightColor: "rgba(255, 255, 255, 0.08)",
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
    borderLeftColor: "#ffb4ab",
    opacity: 0.75,
  },
  queueItemLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: S.md,
  },
  queueIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#201f1f",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  queueItemName: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
    color: "#e5e2e1",
  },
  queueItemMeta: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    color: "#c2c6d8",
    marginTop: 2,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.1,
    textTransform: "uppercase",
  },
});
